let valuesArray = [
	"accountability",
	"action orientation",
	"adaptability",
	"analytical",
	"approachability",
	"attentive",
	"belonging",
	"boldness",
	"care",
	"charity",
	"coaching",
	"collaboration",
	"commitment",
	"communication",
	"community",
	"composure",
	"courage",
	"creativity",
	"customer focus",
	"customer obsession",
	"decisiveness",
	"delight",
	"determination",
	"discipline",
	"diversity",
	"education",
	"empathy",
	"development",
	"ethics",
	"excellence",
	"factualness",
	"fast learning",
	"flexibility",
	"focus",
	"fun",
	"global",
	"humour",
	"growth",
	"hard work",
	"health",
	"honesty",
	"hospitality",
	"human",
	"humility",
	"idealism",
	"impact",
	"improvement",
	"independence",
	"innovation",
	"integrity",
	"leadership",
	"mindfulness",
	"openness",
	"optimistic",
	"passion",
	"principled",
	"professionalism",
	"quality",
	"quick thinking",
	"reactive",
	"resilience",
	"resourceful",
	"respect",
	"responsibility",
	"results oriented",
	"self aware",
	"sense of humour",
	"service",
	"simplicity",
	"speed",
	"sustainability",
	"transparency",
	"trust",
	"versatility"
];

module.exports = valuesArray;
